# Generated by Django 5.2.6 on 2025-09-15 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
